### ISSUE TITLE
(Request) Expose `getInstalledBrowsers` as a submodule

### ISSUE THREAD

**Issue by jvilk** [litixsoft/karma-detect-browsers#10]
I'd like to rely on this package's browser detection features outside of the standard Karma use-case.

Would you accept a PR that refactors `getInstalledBrowsers` into a submodule? (e.g. the root of this project would have `/index.js` and `/detectBrowsers.js`) That way, I can simply `require('karma-detect-browsers/detectBrowsers.js')` from my project.

**Comment by 4kochi** [comment]
An even better solution would be to create a separate npm module for this. You can use this module as boilerplate.

**Comment by jvilk** [comment]
If I created this module, would you depend on it, or would we maintain them separately?

Also, [someone already did this, but their code is out-of-date.](https://github.com/Subash/detect-browsers)

**Comment by 4kochi** [comment]
I would add the module as dependency of this module.

**Comment by 4kochi** [comment]
But indeed it would be a separate module on github and npm

**Comment by jvilk** [comment]
OK, cool. I opened an issue on `detect-browsers` to see if they are willing to go along with this idea (they already have an [npm module](https://www.npmjs.com/package/detect-browsers), but as I mentioned, it's out-of-date).

**Comment by 4kochi** [comment]
Closing for now since we have no free time left for doing this.
