### ISSUE TITLE
2.2.0 breaks our builds

### ISSUE THREAD

**Issue by incompl** [litixsoft/karma-detect-browsers#16]
Builds that do not use the new Microsoft Edge browser support (for example, one of them is Firefox-only) are breaking with this message:

> Warning: Cannot find module 'edge-launcher/Win32/MicrosoftEdgeLauncher.exe' from '/home/travis/build/videojs/video.js/node_modules/karma-detect-browsers/browsers' Use --force to continue.

This broke the build for videojs and at least one of our other projects.

**Comment by LitixThomas** [comment]
Please use fixed version 2.2.1.

**Comment by incompl** [comment]
It worked, thanks for the quick turnaround!

**Comment by forbesjo** [comment]
See #17
