### ISSUE TITLE
Split Chrome and Chromium

### ISSUE THREAD

**Issue by LoveIsGrief** [litixsoft/karma-detect-browsers#22]
They are two separate browsers and should be treated as such since the `karma-chrome-launcher` does. As of now, if chromium is detected, it will pass on "Chrome" and `karma-chrome-launcher` will try to launch Chrome instead of Chromium

**Comment by GreenGremlin** [comment]
I managed to get this working with https://github.com/litixsoft/karma-detect-browsers/pull/27

**Comment by 4kochi** [comment]
Released in `v2.3.0`
