### ISSUE TITLE
Release 2.3.3 is not on NPM

### ISSUE THREAD

**Issue by jackamo** [litixsoft/karma-detect-browsers#36]
Hi!

I see you have made a release for v2.3.3, however, it doesn't seem like the changes have made it to NPM itself, where it sees the latest version as v2.3.2

No biggie, in the mean time we can just specify the git repo directly, and refer to the master branch

EDIT: Ah, I can see the issue is probably the same situation as this one! https://github.com/litixsoft/karma-detect-browsers/issues/32

**Comment by 4kochi** [comment]
Thx for the hint. Done.
