### ISSUE TITLE
Detect PhantomJS

### ISSUE THREAD

**Issue by jvilk** [litixsoft/karma-detect-browsers#8]
The configuration object contains a static boolean for whether or not PhantomJS should be included in the results. It might be better to detect the presence of PhantomJS itself. The `karma-phantomjs-launcher` requires PhantomJS as a peer dependency, so `karma-detect-browsers` could simply detect if `require('phantomjs')` fails.

**Comment by jvilk** [comment]
You could do this with a simple preamble to `getInstalledBrowsers`:

```{js}
function getInstalledBrowsers (browsers) {
        var i, length,
            browserNames = Object.keys(browsers),
            result = [];
        try {
            require('phantomjs');
            // If require did not throw, PhantomJS is installed.
           result.push('PhantomJS');
        } catch (e) {
            // PhantomJS is not installed.
        }
```

**Comment by 4kochi** [comment]
Technically you are right. But we want to cover the case that the `karma-phantomjs-launcher` is installed be should not be used. And if you do not set the option, it is used anyway.

**Comment by jvilk** [comment]
@4kochi I don't understand how that's different from when Firefox is installed but should not be used. In both cases, the user can specify a `postDetection` function to filter browsers.

**Comment by 4kochi** [comment]
Maybe we will remove the option in the next major version.
